import fs from 'fs';
import path from 'path';
import OpenAI from 'openai';
import Transcription from '../models/Transcription.js';

// Setup Mock Fallback DB paths and utility functions
const mockDbPath = './db_fallback.json';

const getMockData = () => {
  if (!fs.existsSync(mockDbPath)) {
    fs.writeFileSync(mockDbPath, JSON.stringify([]));
  }
  try {
    return JSON.parse(fs.readFileSync(mockDbPath, 'utf8'));
  } catch (e) {
    return [];
  }
};

const saveMockData = (data) => {
  fs.writeFileSync(mockDbPath, JSON.stringify(data, null, 2));
};

const mockTranscriptionModel = {
  create: async (doc) => {
    const data = getMockData();
    const newDoc = {
      _id: Math.random().toString(36).substring(2, 9),
      ...doc,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
    data.push(newDoc);
    saveMockData(data);
    return newDoc;
  },
  find: () => {
    const data = getMockData();
    return {
      sort: (sortCriteria) => {
        return data.slice().sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));
      }
    };
  },
  findByIdAndDelete: async (id) => {
    const data = getMockData();
    const index = data.findIndex(item => item._id === id);
    if (index === -1) return null;
    const deleted = data.splice(index, 1)[0];
    saveMockData(data);
    return deleted;
  }
};

const getModel = () => {
  if (process.env.USE_MOCK_DB === 'true') {
    return mockTranscriptionModel;
  }
  return Transcription;
};

// Initialize OpenAI/Groq API client
const getOpenAIClient = () => {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey || apiKey === 'your_openai_api_key_here' || apiKey.trim() === '') {
    return null; // Return null to trigger mock/demo mode
  }
  
  // Auto-detect Groq keys
  if (apiKey.startsWith('gsk_')) {
    console.log('[INFO] Groq API key detected. Configuring Groq Whisper endpoint...');
    return new OpenAI({
      apiKey,
      baseURL: 'https://api.groq.com/openai/v1',
    });
  }
  
  return new OpenAI({ apiKey });
};

// @desc    Upload audio file and transcribe
// @route   POST /api/transcribe
// @access  Public
export const transcribeAudio = async (req, res) => {
  let filePath = null;
  try {
    if (!req.file) {
      return res.status(400).json({ success: false, error: 'No audio file uploaded.' });
    }

    filePath = req.file.path;
    const originalName = req.file.originalname || req.file.filename;

    console.log(`Received file: ${originalName}, Size: ${req.file.size} bytes`);

    const openai = getOpenAIClient();
    let transcriptionText = '';

    if (!openai) {
      console.warn('[WARNING] OPENAI_API_KEY is not configured. Running in Mock Transcription mode.');
      transcriptionText = `[Demo Mode] This is a mock transcription of your file "${originalName}".

To enable real voice transcription:
1. Open "server/.env"
2. Replace "your_openai_api_key_here" with your actual OpenAI API Key.
3. Restart the server.

Mock Text: "Hello! This is a sample speech-to-text transcription generated by the demo server fallback. The audio upload and pipeline are fully working."`;
    } else {
      // Determine model based on key type
      const isGroq = process.env.OPENAI_API_KEY?.startsWith('gsk_');
      const model = isGroq ? 'whisper-large-v3' : 'whisper-1';

      console.log(`Sending audio to ${isGroq ? 'Groq' : 'OpenAI'} Whisper API using model: ${model}...`);
      const response = await openai.audio.transcriptions.create({
        file: fs.createReadStream(filePath),
        model: model,
      });
      transcriptionText = response.text;
      console.log('Transcription successful!');
    }

    // Save transcription details in the database
    const newTranscription = await getModel().create({
      filename: originalName,
      transcription: transcriptionText,
    });

    // Delete temporary file
    fs.unlinkSync(filePath);
    filePath = null; // Mark as deleted

    return res.status(201).json({
      success: true,
      data: newTranscription,
    });
  } catch (error) {
    console.error('Error in transcribeAudio:', error);

    // Clean up temporary file in case of error
    if (filePath && fs.existsSync(filePath)) {
      try {
        fs.unlinkSync(filePath);
      } catch (cleanupError) {
        console.error('Failed to clean up file after error:', cleanupError);
      }
    }

    return res.status(500).json({
      success: false,
      error: error.message || 'An error occurred during the transcription process.',
    });
  }
};

// @desc    Get all past transcriptions
// @route   GET /api/transcriptions
// @access  Public
export const getTranscriptions = async (req, res) => {
  try {
    const history = await getModel().find({}).sort({ createdAt: -1 });
    return res.status(200).json({
      success: true,
      count: history.length,
      data: history,
    });
  } catch (error) {
    console.error('Error in getTranscriptions:', error);
    return res.status(500).json({
      success: false,
      error: 'Failed to fetch transcription history.',
    });
  }
};

// @desc    Delete a transcription from database
// @route   DELETE /api/transcriptions/:id
// @access  Public
export const deleteTranscription = async (req, res) => {
  try {
    const { id } = req.params;
    const transcription = await getModel().findByIdAndDelete(id);
    if (!transcription) {
      return res.status(404).json({ success: false, error: 'Transcription not found' });
    }
    return res.status(200).json({
      success: true,
      message: 'Transcription deleted successfully',
    });
  } catch (error) {
    console.error('Error in deleteTranscription:', error);
    return res.status(500).json({
      success: false,
      error: 'Failed to delete transcription.',
    });
  }
};

